//! C++ code generator.
//!
//! Output shape:
//! ```cpp
//! #pragma pack(push, 1)
//! class PlayerStruct { // optional comment
//! public:
//!     int32_t health; // 0x0000 player HP
//!     float   speed;  // 0x0004
//! }; // Size: 0x0008
//! static_assert(sizeof(PlayerStruct) == 0x8);
//! #pragma pack(pop)
//! ```

use std::collections::HashSet;

use super::{CodeGenerator, FieldKind, Language, PrimKind, resolve_fields, resolved_class_size, sanitize_ident};
use crate::node::registry::NodeRegistry;
use crate::project::Project;

pub struct CppCodeGenerator;

impl CppCodeGenerator {
    fn prim_type(p: PrimKind) -> &'static str {
        match p {
            PrimKind::Int8   => "int8_t",
            PrimKind::Int16  => "int16_t",
            PrimKind::Int32  => "int32_t",
            PrimKind::Int64  => "int64_t",
            PrimKind::UInt8  => "uint8_t",
            PrimKind::UInt16 => "uint16_t",
            PrimKind::UInt32 => "uint32_t",
            PrimKind::UInt64 => "uint64_t",
            PrimKind::Float  => "float",
            PrimKind::Double => "double",
            PrimKind::Bool   => "bool",
        }
    }

    fn int_type_for_size(size: u8) -> &'static str {
        match size {
            1 => "int8_t",
            2 => "int16_t",
            8 => "int64_t",
            _ => "int32_t",
        }
    }

}

impl CodeGenerator for CppCodeGenerator {
    fn language(&self) -> Language { Language::Cpp }

    fn generate(&self, project: &Project, registry: &NodeRegistry) -> String {
        let mut out = String::new();

        out.push_str("// Generated by nemclass-rs\n");
        out.push_str("#pragma once\n");
        out.push_str("#include <cstdint>\n");
        out.push_str("#include <cassert>\n");
        out.push('\n');

        // Enums first
        let enums: Vec<_> = project.enums.iter().collect();
        if !enums.is_empty() {
            for e in &enums {
                let ename = sanitize_ident(&e.name);
                let underlying = Self::int_type_for_size(e.size);
                out.push_str(&format!("enum class {ename} : {underlying}\n{{\n"));
                let last = e.values.len().saturating_sub(1);
                for (i, (vname, vval)) in e.values.iter().enumerate() {
                    let vname = sanitize_ident(vname);
                    if i < last {
                        out.push_str(&format!("    {vname} = {vval},\n"));
                    } else {
                        out.push_str(&format!("    {vname} = {vval}\n"));
                    }
                }
                out.push_str("};\n\n");
            }
        }

        // Classes
        out.push_str("#pragma pack(push, 1)\n\n");

        for class in project.classes_in_order() {
            let cname = sanitize_ident(&class.name);
            // Use resolved size so ClassInstance fields count their target's
            // real byte width rather than the placeholder 0 from memory_size().
            let total_size = resolved_class_size(class, project, &mut HashSet::new());

            // Class header
            out.push_str(&format!("class {cname}"));
            if !class.comment.is_empty() {
                out.push_str(&format!(" // {}", class.comment));
            }
            out.push_str("\n{\npublic:\n");

            let fields = resolve_fields(class, project, registry);

            for f in &fields {
                let comment_part = if f.comment.is_empty() {
                    String::new()
                } else {
                    format!(" {}", f.comment)
                };
                let offset_comment = format!(" //0x{:04X}{comment_part}", f.offset);

                let line = match &f.kind {
                    FieldKind::Primitive(p) => {
                        format!("    {} {};{}\n", Self::prim_type(*p), f.name, offset_comment)
                    }
                    FieldKind::RawBytes(n) => {
                        format!("    uint8_t {}[{}];{}\n", f.name, n, offset_comment)
                    }
                    FieldKind::Pointer(Some(target)) => {
                        format!("    {target}* {};{}\n", f.name, offset_comment)
                    }
                    FieldKind::Pointer(None) => {
                        format!("    void* {};{}\n", f.name, offset_comment)
                    }
                    FieldKind::ClassInstance(tname) => {
                        format!("    {tname} {};{}\n", f.name, offset_comment)
                    }
                    FieldKind::Array { count } => {
                        // Untyped array → raw byte array
                        format!("    uint8_t {}[{}];{}\n", f.name, count, offset_comment)
                    }
                    FieldKind::Utf8Text(len) => {
                        format!("    char {}[{}];{}\n", f.name, len, offset_comment)
                    }
                    FieldKind::Utf16Text(len) => {
                        // len is byte count; each wchar_t is 2 bytes.
                        // div_ceil so an odd byte length rounds up rather than
                        // silently dropping the trailing byte.
                        let char_count = len.div_ceil(2);
                        format!("    wchar_t {}[{}];{}\n", f.name, char_count, offset_comment)
                    }
                };
                out.push_str(&line);
            }

            out.push_str(&format!("}}; //Size: 0x{total_size:04X}\n"));
            out.push_str(&format!(
                "static_assert(sizeof({cname}) == 0x{total_size:X});\n\n"
            ));
        }

        out.push_str("#pragma pack(pop)\n");

        out
    }
}
