//! C# code generator.
//!
//! Output shape:
//! ```csharp
//! using System.Runtime.InteropServices;
//!
//! [StructLayout(LayoutKind.Explicit, CharSet = CharSet.Ansi)]
//! public struct PlayerStruct // optional comment
//! {
//!     [FieldOffset(0x0)]
//!     public readonly int health; // player HP
//!     [FieldOffset(0x4)]
//!     public readonly float speed;
//! }
//! ```

use super::{CodeGenerator, FieldKind, Language, PrimKind, resolve_fields, sanitize_ident};
use crate::node::registry::NodeRegistry;
use crate::node::vector::FloatWidth;
use crate::project::Project;
// Note: C# generator does not currently emit a sizeof assertion (C# structs with
// `unsafe fixed` arrays require an `unsafe` context for Marshal.SizeOf). The
// resolved total size is correct when read from resolve_fields offsets.

pub struct CSharpCodeGenerator;

impl CSharpCodeGenerator {
    fn prim_type(p: PrimKind) -> &'static str {
        match p {
            PrimKind::Int8   => "sbyte",
            PrimKind::Int16  => "short",
            PrimKind::Int32  => "int",
            PrimKind::Int64  => "long",
            PrimKind::UInt8  => "byte",
            PrimKind::UInt16 => "ushort",
            PrimKind::UInt32 => "uint",
            PrimKind::UInt64 => "ulong",
            PrimKind::Float  => "float",
            PrimKind::Double => "double",
            PrimKind::Bool   => "bool",
        }
    }

    fn int_type_for_size(size: u8) -> &'static str {
        match size {
            1 => "sbyte",
            2 => "short",
            8 => "long",
            _ => "int",
        }
    }

    fn float_type(w: FloatWidth) -> &'static str {
        match w {
            FloatWidth::F32 => "float",
            FloatWidth::F64 => "double",
        }
    }
}

impl CodeGenerator for CSharpCodeGenerator {
    fn language(&self) -> Language { Language::CSharp }

    fn generate(&self, project: &Project, registry: &NodeRegistry) -> String {
        let mut out = String::new();

        out.push_str("// Generated by nemclass-rs\n");
        out.push_str("// Warning: The C# code generator doesn't support all node types!\n\n");
        out.push_str("using System.Runtime.InteropServices;\n\n");

        // Enums
        for e in &project.enums {
            let ename = sanitize_ident(&e.name);
            let underlying = Self::int_type_for_size(e.size);
            out.push_str(&format!("public enum {ename} : {underlying}\n{{\n"));
            let last = e.values.len().saturating_sub(1);
            for (i, (vname, vval)) in e.values.iter().enumerate() {
                let vname = sanitize_ident(vname);
                if i < last {
                    out.push_str(&format!("    {vname} = {vval},\n"));
                } else {
                    out.push_str(&format!("    {vname} = {vval}\n"));
                }
            }
            out.push_str("}\n\n");
        }

        // Classes
        for class in project.classes_in_order() {
            let cname = sanitize_ident(&class.name);

            out.push_str("[StructLayout(LayoutKind.Explicit, CharSet = CharSet.Ansi)]\n");
            out.push_str(&format!("public struct {cname}"));
            if !class.comment.is_empty() {
                out.push_str(&format!(" // {}", class.comment));
            }
            out.push_str("\n{\n");

            let fields = resolve_fields(class, project, registry);

            for f in &fields {
                let comment_part = if f.comment.is_empty() {
                    String::new()
                } else {
                    format!(" //{}", f.comment)
                };

                match &f.kind {
                    FieldKind::Primitive(p) => {
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public readonly {} {};{}\n",
                            Self::prim_type(*p),
                            f.name,
                            comment_part
                        ));
                    }
                    FieldKind::RawBytes(n) => {
                        // C# unsafe fixed byte array
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public unsafe fixed byte {}[{}];{}\n",
                            f.name, n, comment_part
                        ));
                    }
                    FieldKind::Pointer(_) => {
                        // All pointers become IntPtr in C# (platform-width)
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public readonly IntPtr {};{}\n",
                            f.name, comment_part
                        ));
                    }
                    FieldKind::ClassInstance(tname) => {
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public {} {};{}\n",
                            tname, f.name, comment_part
                        ));
                    }
                    FieldKind::Array { count } => {
                        // Emit as unsafe fixed byte array (untyped raw bytes)
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public unsafe fixed byte {}[{}];{}\n",
                            f.name, count, comment_part
                        ));
                    }
                    FieldKind::Utf8Text(len) => {
                        out.push_str(&format!(
                            "    [MarshalAs(UnmanagedType.ByValTStr, SizeConst = {len})]\n"
                        ));
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public readonly string {};{}\n",
                            f.name, comment_part
                        ));
                    }
                    FieldKind::Utf16Text(len) => {
                        // Emit as a raw byte array rather than a marshalled string.
                        // Using ByValTStr under CharSet.Ansi would marshal 1 byte/char
                        // (half the true width). A fixed byte array is unambiguous,
                        // matches the C++/Rust treatment, and always compiles.
                        // div_ceil so an odd byte length rounds up rather than
                        // silently dropping the trailing byte.
                        let byte_count = len.div_ceil(2) * 2; // keep even for UTF-16
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public unsafe fixed byte {}[{}];{} // UTF-16 LE\n",
                            f.name, byte_count, comment_part
                        ));
                    }
                    FieldKind::Vector { components, width } => {
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public unsafe fixed {} {}[{}];{}\n",
                            Self::float_type(*width), f.name, components, comment_part
                        ));
                    }
                    FieldKind::Matrix { rows, cols, width } => {
                        // C# `fixed` buffers are one-dimensional, so a matrix is
                        // flattened row-major — index it as `m[row * cols + col]`.
                        out.push_str(&format!("    [FieldOffset(0x{:X})]\n", f.offset));
                        out.push_str(&format!(
                            "    public unsafe fixed {} {}[{}];{} // {}x{} row-major\n",
                            Self::float_type(*width),
                            f.name,
                            rows * cols,
                            comment_part,
                            rows,
                            cols
                        ));
                    }
                }
            }

            out.push_str("}\n\n");
        }

        // Trim trailing newline to one
        while out.ends_with("\n\n") {
            out.pop();
        }

        out
    }
}
