//! Rust code generator.
//!
//! Output shape:
//! ```rust
//! // optional class comment
//! #[repr(C)]
//! pub struct PlayerStruct {
//!     pub health: i32,    // 0x0000 player HP
//!     pub speed: f32,     // 0x0004
//! }
//! ```
//!
//! Enums are emitted as `#[repr(...)]` enums with named variants and associated
//! integer constants. Because we don't know which values map to Rust enum variants
//! at code-gen time (the values come from the target process's data), we emit a
//! tuple-struct newtype + associated const block instead of an `enum` keyword, which
//! is safe for any integer value (including bit-flag sets).


use super::{CodeGenerator, FieldKind, Language, PrimKind, class_size, emitted_array_len, escape_comment, resolve_fields, sanitize_ident};
use crate::node::registry::NodeRegistry;
use crate::project::Project;

pub struct RustCodeGenerator;

impl RustCodeGenerator {
    fn prim_type(p: PrimKind) -> &'static str {
        match p {
            PrimKind::Int8   => "i8",
            PrimKind::Int16  => "i16",
            PrimKind::Int32  => "i32",
            PrimKind::Int64  => "i64",
            PrimKind::UInt8  => "u8",
            PrimKind::UInt16 => "u16",
            PrimKind::UInt32 => "u32",
            PrimKind::UInt64 => "u64",
            PrimKind::Float  => "f32",
            PrimKind::Double => "f64",
            PrimKind::Bool   => "bool",
        }
    }

    /// Map `EnumDescription::size` (byte width) to the Rust integer repr.
    fn int_type_for_size(size: u8) -> &'static str {
        match size {
            1 => "i8",
            2 => "i16",
            8 => "i64",
            _ => "i32",
        }
    }
}

impl CodeGenerator for RustCodeGenerator {
    fn language(&self) -> Language { Language::Rust }

    fn generate(&self, project: &Project, registry: &NodeRegistry) -> String {
        let mut out = String::new();

        out.push_str("// Generated by nemclass-rs\n");
        out.push_str("#![allow(non_camel_case_types, dead_code)]\n\n");

        // Enums: newtype + associated consts so all integer values are representable.
        for e in &project.enums {
            let ename = sanitize_ident(&e.name);
            let repr = Self::int_type_for_size(e.size);

            if e.use_flags {
                // Bit-flag set: newtype wrapper + bit-flag consts
                out.push_str(&format!(
                    "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
                     pub struct {ename}(pub {repr});\n\n\
                     impl {ename} {{\n"
                ));
                for (vname, vval) in &e.values {
                    let vname = sanitize_ident(vname);
                    out.push_str(&format!(
                        "    pub const {vname}: {repr} = {vval};\n"
                    ));
                }
                out.push_str("}\n\n");
            } else {
                // Ordinary enum: emit a proper #[repr] enum.
                // We verify uniqueness isn't required here — the caller is responsible
                // for ensuring discriminants don't collide (mirrors C# behavior).
                out.push_str(&format!(
                    "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
                     #[repr({repr})]\n\
                     pub enum {ename} {{\n"
                ));
                for (vname, vval) in &e.values {
                    let vname = sanitize_ident(vname);
                    out.push_str(&format!("    {vname} = {vval},\n"));
                }
                out.push_str("}\n\n");
            }
        }

        // Structs
        for class in project.classes_in_order() {
            let cname = sanitize_ident(&class.name);
            // Use resolved size so ClassInstance fields count their target's
            // real byte width rather than the placeholder 0 from memory_size().
            let total_size = class_size(class, project);

            // The comment goes on its own line *above* the item, not trailing
            // the `pub struct X` line: appending `// …` there put the opening
            // brace inside the comment, so every class carrying a comment
            // generated a Rust file that does not parse.
            if !class.comment.is_empty() {
                out.push_str(&format!("// {}\n", escape_comment(&class.comment)));
            }
            out.push_str("#[repr(C)]\n");
            out.push_str(&format!("pub struct {cname} {{\n"));

            let fields = resolve_fields(class, project, registry);

            for f in &fields {
                let comment_part = if f.comment.is_empty() {
                    format!(" // 0x{:04X}", f.offset)
                } else {
                    format!(" // 0x{:04X} {}", f.offset, escape_comment(&f.comment))
                };

                // A zero-length member is not representable in this
                // language; the field contributes no bytes, so record it as a
                // comment and keep the layout identical.
                if emitted_array_len(&f.kind) == Some(0) {
                    out.push_str(&format!("    // {} — 0 bytes, omitted{}\n", f.name, comment_part));
                    continue;
                }

                let line = match &f.kind {
                    FieldKind::Primitive(p) => {
                        format!("    pub {}: {},{}\n", f.name, Self::prim_type(*p), comment_part)
                    }
                    FieldKind::RawBytes(n) => {
                        format!("    pub {}: [u8; {}],{}\n", f.name, n, comment_part)
                    }
                    FieldKind::Pointer(Some(target)) => {
                        format!("    pub {}: *mut {},{}\n", f.name, target, comment_part)
                    }
                    FieldKind::Pointer(None) => {
                        format!("    pub {}: usize,{}\n", f.name, comment_part)
                    }
                    FieldKind::ClassInstance(tname) => {
                        format!("    pub {}: {},{}\n", f.name, tname, comment_part)
                    }
                    FieldKind::Array { count } => {
                        format!("    pub {}: [u8; {}],{}\n", f.name, count, comment_part)
                    }
                    FieldKind::Utf8Text(len) => {
                        format!("    pub {}: [u8; {}],{}\n", f.name, len, comment_part)
                    }
                    FieldKind::Utf16Text(len) => {
                        // Store as u16 array; len is byte count.
                        // div_ceil so an odd byte length rounds up rather than
                        // silently dropping the trailing byte.
                        let char_count = len.div_ceil(2);
                        format!(
                            "    pub {}: [u16; {}],{}\n",
                            f.name, char_count, comment_part
                        )
                    }
                    FieldKind::Vector { components, width } => {
                        format!(
                            "    pub {}: [{}; {}],{}\n",
                            f.name, width.rust_ty(), components, comment_part
                        )
                    }
                    FieldKind::Matrix { rows, cols, width } => {
                        // Row-major: the outer array indexes rows.
                        format!(
                            "    pub {}: [[{}; {}]; {}],{}\n",
                            f.name, width.rust_ty(), cols, rows, comment_part
                        )
                    }
                };
                out.push_str(&line);
            }

            out.push_str("}\n\n");
            out.push_str(&format!(
                "const _: () = assert!(std::mem::size_of::<{cname}>() == 0x{total_size:X});\n\n"
            ));
        }

        // Trim trailing double-newline
        while out.ends_with("\n\n") {
            out.pop();
        }

        out
    }
}
