//! Project-directory scaffolding + TypeScript type generation.
//!
//! [`write_script_scaffold`] writes the three files a `project.nemclass`
//! directory needs so `src/*.ts` scripts get editor autocomplete against the
//! host API and the event payloads:
//!
//! - `package.json`   — declares the project's script package + `nemclass.d.ts`.
//! - `tsconfig.json`  — points the compiler at `src/` and the ambient types.
//! - `nemclass.d.ts`  — ambient declarations for the `nemclass` global (host
//!   functions + `on(...)` event registration) and the six lifecycle event
//!   payload shapes.
//!
//! **This module is intentionally *not* feature-gated.** It is pure string/file
//! I/O with no v8 dependency, so it always compiles and is unit-tested in the
//! default build. The generated `.d.ts` is derived from a single in-crate source
//! of truth — [`EVENT_KINDS`] and the host-fn list mirrored from
//! [`crate::events::Event`] / [`crate::host_api`] — so the declarations cannot
//! silently drift from the Rust event enum. A guard test
//! (`event_kinds_match_the_event_enum`) fails if a new [`crate::events::Event`]
//! variant is added without updating [`EVENT_KINDS`].

use std::fs;
use std::path::Path;

/// The six lifecycle events plus the user-raised `Custom` event, as the JS-facing
/// handler names scripts register with `nemclass.on(<name>, fn)`.
///
/// This is the single source of truth the `.d.ts` `EventName` union and the
/// per-event handler typings are generated from. Kept in lock-step with
/// [`crate::events::Event::kind`] by `event_kinds_match_the_event_enum`.
pub const EVENT_KINDS: &[&str] = &[
    "OnProjectLoad",
    "OnAttach",
    "OnDetach",
    "ClassAddressUpdated",
    "GlobalVariableUpdated",
    "Custom",
];

/// Writes `package.json`, `tsconfig.json`, and `nemclass.d.ts` into
/// `project_dir` (a `project.nemclass` directory), creating the directory (and
/// its `src/`) if needed.
///
/// Overwrites the three generated files if they already exist — they are derived
/// artifacts, so regenerating on project open keeps the type surface current. It
/// does **not** touch anything under `src/`.
pub fn write_script_scaffold(project_dir: &Path) -> std::io::Result<()> {
    fs::create_dir_all(project_dir.join("src"))?;

    fs::write(project_dir.join("package.json"), PACKAGE_JSON)?;
    fs::write(project_dir.join("tsconfig.json"), TSCONFIG_JSON)?;
    fs::write(project_dir.join("nemclass.d.ts"), generate_dts())?;

    Ok(())
}

/// `package.json` scaffolded on project creation. Static: it only names the
/// package and points editors at the generated ambient declarations.
const PACKAGE_JSON: &str = r#"{
  "name": "nemclass-project",
  "version": "0.1.0",
  "private": true,
  "description": "nemclass scripting project — host-API types in nemclass.d.ts",
  "types": "./nemclass.d.ts"
}
"#;

/// `tsconfig.json` scaffolded on project creation. Includes `src/` and the
/// ambient `nemclass.d.ts` so scripts type-check against the host API.
const TSCONFIG_JSON: &str = r#"{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ES2020",
    "moduleResolution": "node",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "noEmit": true,
    "types": []
  },
  "include": ["src/**/*.ts", "nemclass.d.ts"]
}
"#;

/// Builds the ambient `nemclass.d.ts` from [`EVENT_KINDS`] and the host-API
/// surface, so the declarations track the Rust event enum / host fns.
fn generate_dts() -> String {
    // The `EventName` union, derived from EVENT_KINDS (single source of truth).
    let event_union = EVENT_KINDS
        .iter()
        .map(|k| format!("\"{k}\""))
        .collect::<Vec<_>>()
        .join(" | ");

    format!(
        r#"// GENERATED by nemclass write_script_scaffold — do not edit by hand.
// Ambient declarations for the `nemclass` scripting host API and lifecycle
// events. Regenerated whenever a project is (re)opened.

/** A resolved absolute address in the target process. */
type Address = number;

/** The lifecycle/custom events a script can subscribe to via `nemclass.on`. */
type EventName = {event_union};

/** Payload for `OnProjectLoad`: the loaded project directory path. */
interface OnProjectLoadEvent {{ kind: "OnProjectLoad"; path: string; }}

/** Payload for `OnAttach`: the attached process id and (best-effort) name. */
interface OnAttachEvent {{ kind: "OnAttach"; pid: number; name: string | null; }}

/** Payload for `OnDetach`: no data — the target is gone. */
interface OnDetachEvent {{ kind: "OnDetach"; }}

/** Payload for `ClassAddressUpdated`: the class UUID and its new base address. */
interface ClassAddressUpdatedEvent {{ kind: "ClassAddressUpdated"; class: string; address: Address; }}

/** A named pointer into the target (name + resolved address). */
interface GlobalVariable {{ name: string; address: Address; }}

/** Payload for `GlobalVariableUpdated`: the changed global variable. */
interface GlobalVariableUpdatedEvent {{ kind: "GlobalVariableUpdated"; variable: GlobalVariable; }}

/** Payload for a user-raised `Custom` event. */
interface CustomEvent {{ kind: "Custom"; name: string; payload: {{ text: string; attrs: Record<string, string>; }}; }}

/** Discriminated union of every event payload dispatched to handlers. */
type NemclassEvent =
  | OnProjectLoadEvent
  | OnAttachEvent
  | OnDetachEvent
  | ClassAddressUpdatedEvent
  | GlobalVariableUpdatedEvent
  | CustomEvent;

/** A description of a custom (enum) type declared via `declare_type`. */
interface EnumDescription {{
  name: string;
  /** Underlying size in bytes: 1, 2, 4, or 8 (default 4). */
  size?: number;
  /** Whether the values are bit-flags (default false). */
  use_flags?: boolean;
  /** Ordered `[variantName, value]` members. */
  values: [string, number][];
}}

/** The host API exposed to scripts as the global `nemclass` object. */
interface NemclassHost {{
  /**
   * IDA-style byte-pattern scan over a loaded module. Tokens are hex bytes
   * (`4A`), full wildcards (`??`/`?`), or nibble wildcards (`4?`/`?8`).
   * Returns every absolute match address. Not available during
   * `tryResolveClassAddress` (throws if called from a resolver).
   */
  pattern_scan(module: string, pattern: string): Address[];

  /** Declare a custom (enum) type into the host's model. */
  declare_type(descriptor: EnumDescription): void;

  /**
   * Declare a class by name with an address formula (e.g. `"game.exe"+0x10`).
   * The host creates the class in the open project.
   */
  declare_class(name: string, addressFormula: string): void;

  /** Log a message through the host (appears in the app's log). */
  log(msg: string): void;

  /**
   * Register a handler for a lifecycle/custom event. The handler receives the
   * matching event payload. As an alternative, a module may `export` a function
   * named `onAttach` / `onDetach` / `onProjectLoad` / `classAddressUpdated` /
   * `globalVariableUpdated` / `tryResolveClassAddress` and it is dispatched
   * automatically.
   */
  on(event: EventName, handler: (e: NemclassEvent) => void): void;

  /**
   * Register the `TryResolveClassAddress` resolver: given a query it returns an
   * address to claim the class, or `null`/`undefined` to defer. Host functions
   * are unavailable inside this resolver.
   */
  tryResolveClassAddress?: (q: {{ pid: number; class: string; }}) => Address | null | undefined;
}}

declare global {{
  const nemclass: NemclassHost;
}}

export {{}};
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::events::Event;

    #[test]
    fn writes_the_three_scaffold_files() {
        let dir = tempfile::tempdir().unwrap();
        let proj = dir.path().join("project.nemclass");
        write_script_scaffold(&proj).unwrap();

        assert!(proj.join("package.json").is_file(), "package.json written");
        assert!(proj.join("tsconfig.json").is_file(), "tsconfig.json written");
        assert!(proj.join("nemclass.d.ts").is_file(), "nemclass.d.ts written");
        assert!(proj.join("src").is_dir(), "src/ created");
    }

    #[test]
    fn dts_contains_host_api_and_event_symbols() {
        let dts = generate_dts();
        // Host functions.
        for sym in ["pattern_scan", "declare_type", "declare_class", "log", "on"] {
            assert!(dts.contains(sym), "d.ts declares host fn `{sym}`");
        }
        // The six event payload interfaces + the union.
        for sym in [
            "NemclassEvent",
            "OnProjectLoadEvent",
            "OnAttachEvent",
            "OnDetachEvent",
            "ClassAddressUpdatedEvent",
            "GlobalVariableUpdatedEvent",
            "CustomEvent",
            "tryResolveClassAddress",
            "declare const",
        ] {
            // (`declare const` guards the ambient `nemclass` global.)
            let needle = if sym == "declare const" { "const nemclass" } else { sym };
            assert!(dts.contains(needle), "d.ts declares `{sym}`");
        }
        // Every EVENT_KIND appears in the EventName union.
        for k in EVENT_KINDS {
            assert!(dts.contains(&format!("\"{k}\"")), "EventName union has `{k}`");
        }
    }

    #[test]
    fn package_and_tsconfig_point_at_the_dts() {
        assert!(PACKAGE_JSON.contains("nemclass.d.ts"));
        assert!(TSCONFIG_JSON.contains("nemclass.d.ts"));
        assert!(TSCONFIG_JSON.contains("src/**/*.ts"));
    }

    /// Guard: [`EVENT_KINDS`] must stay in lock-step with the [`Event`] enum, so
    /// the generated `.d.ts` can never silently omit a new event variant.
    #[test]
    fn event_kinds_match_the_event_enum() {
        // One representative value per variant; `Event::kind()` is the authority.
        let samples = [
            Event::OnProjectLoad { path: String::new() },
            Event::OnAttach { pid: 0, name: None },
            Event::OnDetach,
            Event::ClassAddressUpdated {
                class: uuid::Uuid::nil(),
                address: 0,
            },
            Event::GlobalVariableUpdated {
                variable: crate::events::GlobalVariable::new("x", 0),
            },
            Event::Custom {
                name: String::new(),
                payload: crate::events::CustomPayload::empty(),
            },
        ];
        let from_enum: Vec<&str> = samples.iter().map(|e| e.kind()).collect();
        assert_eq!(
            from_enum, EVENT_KINDS,
            "EVENT_KINDS drifted from Event::kind(); update scaffold::EVENT_KINDS"
        );
    }
}
