[package]
name = "nemclass-ui"
version.workspace = true
edition.workspace = true

[dependencies]
nemclass-core.workspace = true
nemclass-model.workspace = true
nemclass-script.workspace = true
egui.workspace = true
egui_extras.workspace = true
eframe.workspace = true
uuid.workspace = true
libc.workspace = true
