PACKAGE_NAME="nemclass_mod"
PACKAGE_VERSION="2.0"
CLEAN="make clean"
MAKE[0]="make all KDIR=/lib/modules/$kernelver/build"
BUILT_MODULE_NAME[0]="nemclass_mod"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
AUTOINSTALL="yes"